# Generated by Django 5.1.1 on 2024-10-03 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='coche_vendido',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
